int x;
int *p;
int **pp;
int ***ppp;
char ****pppp;
int *****ppppp;
const int ci;
volatile int vi;
const volatile int cvi;
int * const pc;
static int si;
extern int ei;
register int ri;
auto int ai;
unsigned int ui;
signed int si2;
short int shi;
long int li;
long long int lli;
unsigned u;
long l;
short s;
long long ll;
int a, b;
int *x1, **x2;
int *y1, y2, **y3;
unsigned *ua1, ua2**, ua3***;
long *la1, la2**;
int cp1****, cp2*****;
int (*ptr1)[10];
int *(*ptr2);
int (**ptr3);
